# Generated by Django 5.1 on 2024-08-28 23:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_admin_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='wallet_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
