# Generated by Django 5.1 on 2024-09-30 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_student_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='nft_images/'),
            preserve_default=False,
        ),
    ]
