# Generated by Django 5.1 on 2024-10-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_nft_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='minting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='election_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
