# Generated by Django 5.1 on 2024-10-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_nft_minting_link_poll_election_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='election_id',
        ),
    ]
